### ISSUE TITLE
More detailed Installation guide

### ISSUE THREAD

**Issue by squadwuschel** [ivanbuzyka/Sitecore.SolrCloudConfiguration#1]
Hi,

I am really new to sitecore and I try to setup a XP1 installation. And currently  I am not able so setup a simple server with Zookeeper on it and one SOLR Instance. When I try to do so I got Installation errors when I try to start the xconnect-solr.json

I've already created a https://sitecore.stackexchange.com/questions/12597/solr-and-zookeeper-setup post there and I've tried to set it up but it's not working perhaps you could go into more details in your wiki what you have to do that its working e.g. in part 4. Install Solr Nodes

**Comment by ivanbuzyka** [comment]
As far as I can see from that stackexchange article, you resolved the question. Unfortunately, I have a bit lack of time to finish these wiki articles.
I did that installation in a little bit different way. I created SolrCloud nodes and Sitecore collections manually (without help of SIF). That is actually really easy: https://doc.sitecore.net/sitecore_experience_platform/setting_up_and_maintaining/search_and_indexing/walkthrough_setting_up_solrcloud

**Comment by squadwuschel** [comment]
Yes the core problem at the moment is, that the SOLR json files from Sitecore are not ready for the cloud installation of sitecore and you have to create the indexes by hand because when you create the indexes with the Json file each index is only connected to one solr  node
